Error in lt_abridged(Deaths = Deaths, Exposures = Exposures, nMx = nMx,  : 
  extrapFrom <= max(Age) is not TRUE


Error in base::try(E, TRUE) : objeto 'E' no encontrado


Error in base::try(E, TRUE) : objeto 'E' no encontrado


Error in lt_abridged(Deaths = Deaths, Exposures = Exposures, nMx = nMx,  : 
  extrapFrom <= max(Age) is not TRUE


Error in lt_id_Ll_S(nLx, lx, Age, AgeInt, N = 5) : 
  all(nLx >= 0, nLx[Age < 100] > 0, nLx[-n] < (radix * N)) is not TRUE


Error: '...' usado en un contexto incorrecto


Error in lt_id_Ll_S(nLx, lx, Age, AgeInt, N = 5) : 
  all(nLx >= 0, nLx[Age < 100] > 0, nLx[-n] < (radix * N)) is not TRUE


Error: inesperado ')' in:
"nLx[-n] < (radix * 
          N))"


Error: inesperado ')' in:
"nLx[-n] < (radix * 
          N))"


